### PR TITLE
Fix tap can not running well error

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: aisuko <urakiny@gmail.com>

fix: #67 #70 #60

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you for this, @Aisuko. This looks like a strong update. 👍 I'll checkout and help validate by building locally and testing out the adapters functions. 

There are a couple of go.sum and go.mod conflicts given the recent update with the apimachinery dependency - https://github.com/layer5io/meshery-linkerd/pull/99/conflicts

**Comment by Aisuko** [comment]
@leecalcote  We can fix the issue at first and do new PR(Use the layer5io/go-kit as the common framework) which we discussed before

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
An item to watchout for:

I left "default" as the namespace value when provisioning Linkerd from the Meshery UI, which resulted in -

Screen Shot 2020-09-22 at 10 18 58 PM

**Comment by leecalcote** [comment]
I can verify that the download cache works. ✔️ 

I can also say that Linkerd and Kuma don't play well on the same cluster.

**Comment by Aisuko** [comment]
> An item to watchout for:
> 
> I left "default" as the namespace value when provisioning Linkerd from the Meshery UI, which resulted in -
> 
> Screen Shot 2020-09-22 at 10 18 58 PM
Nice catching, that may the  ` linkerd pre-checking`  process result, I have a consider should we outside the default namespace when deploy linkerd, this issue I will fix in nice PR(optimization of the `pre-checking`)

**Pull request merged**
