### PR TITLE
Changed to download Linkerd-cli of the latest stable version

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

* Changed to download Linkerd-cli of the latest stable version
* Changed the unit test cases to hit error just failed

### CODE REVIEW

**Comment by antweiss** [comment]
Thanks for tackling this @Aisuko ! Building right now, but shouldn't it be accompanied by changing the namespace flag for linkerd back to '-l' ?

**Comment by Aisuko** [comment]
> Thanks for tackling this @Aisuko ! Building right now, but shouldn't it be accompanied by changing the namespace flag for linkerd back to '-l' ?





> Thanks for tackling this @Aisuko ! Building right now, but shouldn't it be accompanied by changing the namespace flag for linkerd back to '-l' ?

Thanks for your quick reply. I have a consider here, Is there anyway make us active rather than passive. I mean we can do some mechanism for this and that will not need us to change source code every time.

**Comment by antweiss** [comment]
Ideas: we could of course parse the help output of linkerd CLI and try to find appropriate flag values from that, but that's very unreliable.
I think a better approach would be to go with defined stable versions and test each version fo linkerd for compatibility before upgrading.
For edge versions (which would also be nice to support) - we can go with the latest but with low reliability guarantees. And we need to improve error notification - so if anything fails during install stage - we'd show it in browser,  not only in the logs.

**Comment by antweiss** [comment]
I was busy, but I expect to test your changes tomorrow.

**Comment by naturalett** [comment]
@Aisuko 
I barely saw that the full name flag was changed so try to write it as:
- --linkerd-namespace

rather than the shortening flag as -l or -L

**Comment by Aisuko** [comment]
> @Aisuko
> I barely saw that the full name flag was changed so try to write it as:
> 
> * --linkerd-namespace
> 
> rather than the shortening flag as -l or -L

Good point. I will check the `linkerd-cli` flags and make sure what we can add.

**Comment by Aisuko** [comment]
@leecalcote I have been change the Test case to print the command output below. So, It will work well. And add the cache to CI 

```
GOROOT=/usr/local/Cellar/go/1.14.1/libexec #gosetup
GOPATH=/Users/bowen/go #gosetup
/usr/local/Cellar/go/1.14.1/libexec/bin/go test -c -o /private/var/folders/cw/jxrpph_5283f34lklh_z5b580000gn/T/___TestExecute_in_github_com_layer5io_meshery_linkerd_linkerd -gcflags "all=-N -l" github.com/layer5io/meshery-linkerd/linkerd #gosetup
/usr/local/Cellar/go/1.14.1/libexec/bin/go tool test2json -t /Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=localhost:60110 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /private/var/folders/cw/jxrpph_5283f34lklh_z5b580000gn/T/___TestExecute_in_github_com_layer5io_meshery_linkerd_linkerd -- -test.v -test.run ^TestExecute$ #gosetup
API server listening at: 127.0.0.1:60110
=== RUN   TestExecute
    TestExecute: install_test.go:81: kubernetes-api
        --------------
        √ can initialize the client
        √ can query the Kubernetes API
        
        kubernetes-version
        ------------------
        √ is running the minimum Kubernetes API version
        √ is running the minimum kubectl version
        
        pre-kubernetes-setup
        --------------------
        √ control plane namespace does not already exist
        √ can create non-namespaced resources
        √ can create ServiceAccounts
        √ can create Services
        √ can create Deployments
        √ can create CronJobs
        √ can create ConfigMaps
        √ can create Secrets
        √ can read Secrets
        √ no clock skew detected
        
        pre-kubernetes-capability
        -------------------------
        √ has NET_ADMIN capability
        √ has NET_RAW capability
        
        linkerd-version
        ---------------
        √ can determine the latest version
        √ cli is up-to-date
        
        Status check results are √
        
--- PASS: TestExecute (9.30s)
PASS

Debugger finished with exit code 0
```

**Comment by leecalcote** [comment]
@Aisuko @antweiss thank you for this fix. The adapter wasn't able to provision Linkerd otherwise.

**Pull request merged**
