### PR TITLE
fix build status badge, ref #13

### LINKED ISSUE #13: Meshery Adapter for Linkerd build status badge defunct
**Description**
The Meshery project recently switched from TravisCI to GitHub Actions. As such, each of the Meshery repositories need the *build* badges in their [README](blob/master/README.md)s updated. Badges from shields.io are mostly used across the repositories, however, shields.io support for GitHub Actions badge [seems pending](https://github.com/badges/shields/issues/2574). A number of solutions, including [one from GitHub](https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository), have cropped up. Any should work.

**Expected Behavior**
Each Meshery repository's README should have a build badge showing the current status of that components build.

### PR DESCRIPTION
**Pull request by soc1c**
fix #13

### CODE REVIEW

**Comment by leecalcote** [comment]
@soc1c in order to for this PR to be merged, you'll need to sign your commit. To do so on this PR, you can following the instructions here - https://github.com/layer5io/meshery-linkerd/pull/14/checks?check_run_id=231119429

To so do automatically on all future PRs, these instructions will help - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

Thanks so much for contributing! If you're inclined to participate more, please join the community Slack and say hi! --> http://slack.layer5.io

**Comment by leecalcote** [comment]
@soc1c you'll need to sign your commit following [these instructions](https://github.com/layer5io/meshery-linkerd/pull/14/checks?check_run_id=231119429) in order get this PR merged.

**Comment by soc1c** [comment]
I see. Unfortunately, I don't have the time to read up on this right now. Sorry for the buzz

**Comment by leecalcote** [comment]
Thanks,@soc1c. Given the very small nature of the contribution, risks associated with not having your commit sign are incredibly low. Let's merge this one in.

**Pull request merged**
