### PR TITLE
Fix CI configuration

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: aisuko <urakiny@gmail.com>

fixes: #181

### CODE REVIEW

**Comment by kumarabd** [comment]
@Aisuko Any idea about the static checks?

**Comment by Aisuko** [comment]
> @Aisuko Any idea about the static checks?

No problems

**Comment by leecalcote** [comment]
@Aisuko, do you I think you might be able to resolve the static check error? I'm sure that it doesn't have anything to do with your PR￼, but it would be helpful if you were able to take a look.￼

**Comment by Aisuko** [comment]
> @Aisuko, do you I think you might be able to resolve the static check error? I'm sure that it doesn't have anything to do with your PR￼, but it would be helpful if you were able to take a look.￼

No problems, I will fix the static error of the code.

**Comment by leecalcote** [comment]
Thanks.

**Pull request merged**
