### PR TITLE
Updated go.mod dependency alert

### PR DESCRIPTION
**Pull request by tripathyprateek**
Signed-off-by: tripathyprateek <tripathy.prateek@gmail.com>

Issue #140

### CODE REVIEW

**Comment by tripathyprateek** [comment]
oh okay, I need to change the meshkit version. What version do I need to put there?

**Comment by mgfeller** [comment]
Hi @tripathyprateek thanks for fixing this. Let's keep this version for now. You have to change all the imports from `github.com/layer5io/gokit/` to `github.com/layer5io/meshkit/`, though. I think there is just one.
And it's always a good idea to run `make local-check` before you push, and run tests if there are any. Best is to run the adapter locally and test it using the web UI.

**Comment by tripathyprateek** [comment]
> Hi @tripathyprateek thanks for fixing this. Let's keep this version for now. You have to change all the imports from `github.com/layer5io/gokit/` to `github.com/layer5io/meshkit/`, though. I think there is just one.
> And it's always a good idea to run `make local-check` before you push, and run tests if there are any. Best is to run the adapter locally and test it using the web UI.

Sure, so we should keep the version as it is. I will close this PR then. My bad, I thought it was a small fix so I didnt test it. Will keep that in mind in the future.

**Comment by mgfeller** [comment]
That's ok, no worries. Thanks for your time!

**Pull request closed without merging**
